import type { Metadata } from 'next'
import { Agbalumo } from 'next/font/google'
import './globals.css'

const aglabumo = Agbalumo({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'COINflow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={aglabumo.className}>{children}</body>
    </html>
  )
}
